### ISSUE TITLE
error when calling label_landcover funciton as shown in tutorial

### ISSUE THREAD

**Issue by mponce0** [unige-geohealth/inAccessMod#7]
The `label_landcover` is failing when I used as instructed in the tutorial,
```R
> label_landcover(mainPath, country, mostRecent = TRUE, overwrite = TRUE, defaultLabels = TRUE)
Error in label_landcover(mainPath, country, mostRecent = TRUE, overwrite = TRUE,  :

Processed land cover raster is missing!
```

Same error shows up when trying the example presented in the help of the label_landcover function,
```R
 > country
[1] "Switzerland"
>
> download_boundaries(mainPath, country, adminLevel = 1, type = "gbOpen", alwaysDownload = TRUE)
trying URL 'https://github.com/wmgeolab/geoBoundaries/raw/c0ed7b8/releaseData/gbOpen/CHE/ADM1/geoBoundaries-CHE-ADM1-all.zip'
Content type 'application/zip' length 5546581 bytes (5.3 MB)
==================================================
downloaded 5.3 MB

Done: /.../inAccessMod/Switzerland/data/vBorders/20231210113933/raw/geoBoundaries-CHE-ADM1.shp
[1] TRUE
>
> download_landcover(mainPath, country, alwaysDownload = TRUE, mostRecent = TRUE)Loading raw boundary shapefile...
trying URL 'https://s3-eu-west-1.amazonaws.com/vito.landcover.global/v3.0.1/2019/E000N60/E000N60_PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif'
Content type 'image/tiff' length 67306666 bytes (64.2 MB)
==================================================
downloaded 64.2 MB

Done: /.../inAccessMod/Switzerland/data/rLandcover/20231210113952/raw/Switzerland_PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif
[1] TRUE
>
> label_landcover(mainPath, country, mostRecent = TRUE, overwrite = TRUE, defaultLabels = TRUE)
Error in label_landcover(mainPath, country, mostRecent = TRUE, overwrite = TRUE,  :

Processed land cover raster is missing!
>
```

One more thing, please notice that the help for the ` label_landcover` function has a typo and a possible type mismatch in the first part of its example:
```R
Examples:

# Replace workDir with the actual path to your working directory
## Not run:

mainPath <- "workDir"
intiate_project(mainPath, country)
## End(Not run)
```

typo: `intiate_project(mainPath, country)` --> missing "i" in `initiate_project", also `country` does not look to be a parameter for the function

openjournals/joss-reviews#5879

**Comment by ptimoner** [comment]
@mponce0 Yes, actually the label_landcover function requires a processed landcover layer. This is why you got the message "Processed land cover raster is missing!". In the tutorial it comes after the processing of the input data. To make it clearer we added in the tutorial and in the function help a note about this. We also corrected the example in the help. Indeed, prior operations that were not included in the example are needed in order to obtain a processed landcover layer. 

We also corrected the typo (thanks !) and another issue that could raise when processing the landcover layer only.

Please pull the updated version of the package and let us know if you could run the label_landcover correctly.

Thanks.

https://github.com/openjournals/joss-reviews/issues/5879

**Comment by mponce0** [comment]
Sorry, I'm still seeing the same error after pulling the latest commit d6178d9ee296dca4c9b4c32fd45e3eaa80bad4ef.

Also in the help the `initiative_project` still shows up the `country` argument which as far as I can see is not a valid one.

For `labels_landcover` is there something I'm missing? I'm just following the steps shown in the tutorial or the help function.
Maybe a step-by-step example here could help?

**Comment by ptimoner** [comment]
@mponce0 If you still have the same error, it is likely that the something went wrong with the downloading and processing of the landcover raster. I slightly modified the help, and if you follow the different steps it should work.

1. `initiate_project(mainPath)` #mainPath is your working directory; select Switzerland
2. `country <- "Switzerland"`
3. `download_boundaries(mainPath, country, adminLevel = 1, type = "gbOpen", alwaysDownload = TRUE)`
4. `set_projection(mainPath, country, mostRecent = TRUE, alwaysSet = TRUE, bestCRS = TRUE)` # you will interactively asked to provide a label for the processed boundaries (when setting the projection, the boundary shapefile is processed)
5. `download_landcover(mainPath, country, alwaysDownload = TRUE, mostRecent = TRUE)`
6. `download_population(mainPath, country, alwaysDownload = TRUE)` # Go to Global_2000_2020_Constrained/2019 and select che_ppp_2019_constrained.tif
7. `process_inputs(mainPath, country, "rLandcover", defaultMethods = TRUE, changeRes = FALSE, popCorrection = FALSE)` # you will be interactively asked to provide a label for the landcover raster.
8. `label_landcover(mainPath, country, mostRecent = TRUE, overwrite = TRUE, defaultLabels = TRUE)`

The boundaries as well as the population raster are required to process any input data. For this reason you need to download them and to set the projection before processing the landcover raster. Once you have processed the landcover raster, you can run the `label_landcover` function.

If you still see the error, please let me know which step is causing the issue.

I removed the country argument in the `initiate_project` help, thanks for informing me about this.

**Comment by mponce0** [comment]
Thanks @ptimoner .
Everything appears to be working now, test cases and `label_landcover` function.
